apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # key value pair
  labels:
        app: nginx # same key value pair
spec: # specs for deployment
  selector:
    matchLabels:
      app: nginx # create a connection between deployment and pod | this way deployment will know which pods belong to it
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # config for pod
    metadata:
      labels:
        app: nginx # same key value pair as used for deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec: # specs for service  
  selector:
    app: nginx # create a connection between service and deployment or its pods | service must know which pods are registred with it
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # must match the container port