apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmdb-deployment # key value pair
  labels:
    app: tmdb # same key value pair
spec: # specs for deployment
  selector:
    matchLabels:
      app: tmdb # create a connection between deployment and pod | this way deployment will know which pods belong to it
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # config for pod
    metadata:
      labels:
        app: tmdb # same key value pair as used for deployment
    spec:
      containers:
        - name: tmdb
          image: acrcw/tmdb
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tmdb-service
spec: # specs for service
  selector:
    app: tmdb # create a connection between service and deployment or its pods | service must know which pods are registred with it
  type: NodePort # to assign an external ip to this service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # must match the container port
      nodePort: 32323 # port for external ip address must be between 30000-32767